# vi: ft=yaml.ansible
- name: Arch Provision
  hosts: all
  become: false
  connection: local
  tasks:
    - name: Change user shell to zshrc
      block:
        - name: Install zsh and shell support libraries
          become: true
          community.general.pacman:
            name:
              - zsh
              - zsh-completions
        - name: Update default shell
          become: true
          ansible.builtin.user:
            name: "{{ user_name }}"
            shell: /bin/zsh
    - name: Stat yay binary
      ansible.builtin.stat:
        path: /bin/yay
      register: yay_file
    - name: Install yay
      when: not yay_file.stat.exists
      block:
        - name: Get temp directory
          ansible.builtin.tempfile:
            state: directory
            suffix: _yay
          register: yay_build_dir
        - name: Pull yay git repo
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay.git
            dest: "{{ yay_build_dir.path }}"
            depth: 1
        - name: Make package
          ansible.builtin.command:
            cmd: makepkg --noconfirm -si
            chdir: "{{ yay_build_dir.path }}"
          changed_when: true
        - name: Clean temp directory
          ansible.builtin.file:
            path: "{{ yay_build_dir.path }}"
            state: absent
    - name: Set pacman conf
      become: true
      ansible.builtin.template:
        src: "templates/pacman.conf"
        dest: /etc/pacman.conf
        mode: "0644"
    - name: Sync pacman repositories
      become: true
      ansible.builtin.command:
        cmd: pacman -Sy
      changed_when: true
    - name: Dotfiles
      block:
        - name: Set machine ID file for dotfiles
          ansible.builtin.copy:
            content: "{{ inventory_hostname_short }}"
            dest: "{{ ansible_env.HOME }}/machine_id"
            mode: "0644"
        - name: Install chezmoi library
          become: true
          community.general.pacman:
            name: chezmoi
            state: present
            update_cache: true
        - name: Initialize dotfiles from github
          ansible.builtin.command:
            cmd: chezmoi --no-tty init {{ github_username }}
          changed_when: true
        - name: Check for existing chezmoi config
          ansible.builtin.stat:
            path: "{{ ansible_env.HOME }}/.config/chezmoi/chezmoi.yaml"
          register: chezmoi_config
        - name: Re-add any changed chezmoi files in destination
          ansible.builtin.command:
            cmd: chezmoi re-add
          changed_when: true
        - name: Perform chezmoi initial update
          ansible.builtin.command:
            cmd: chezmoi --no-tty apply -c {{ ansible_env.HOME }}/.local/share/chezmoi/home/dot_config/chezmoi/chezmoi-initial.yaml
          changed_when: true
          when: not chezmoi_config.stat.exists
        - name: Perform regular chezmoi update
          ansible.builtin.command:
            cmd: chezmoi --no-tty apply
          changed_when: true

    - name: Post-dotfiles setup
      block:
        - name: Apply xorg configuration
          become: true
          ansible.builtin.template:
            src: "{{ item }}"
            dest: /etc/X11/xorg.conf.d
            mode: "0644"
          loop: "{{ lookup('fileglob', 'templates/xorg/*', wantlist=True) }}"
        - name: Enable SDDM login manager at boot
          become: true
          ansible.builtin.systemd:
            name: sddm
            enabled: true
        - name: Enable CUPS at boot
          become: true
          ansible.builtin.systemd:
            name: cups
            enabled: true
        - name: Set SDDM configuration
          become: true
          ansible.builtin.lineinfile:
            path: /usr/share/sddm/scripts/Xsetup
            regexp: ^setxkbmap -layout us -option ctrl\:nocaps
            line: setxkbmap -layout us -option ctrl:nocaps
